language: ruby

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby-19mode
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

  include:
  - rvm: 2.2
    addons:
      code_climate:
        repo_token:
          secure: GkZRpKpf6hYEaWFf4NvB7OgbF3obhbDvzzbLY5AVutccgF4ifk2cVLyzqqRwmYiwAlVze08JePddFZxQppcDo4AuuMDU8+SDt16jr20GAI4S/+FrV8J6p7suXEQNvQxuZONFDQpi/K9jAHlJgzEVYLhWT72v2JH9fghnfVcv13w=

  fast_finish: true